services:
  amazon-pa:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - nginx_bridge

networks:
  nginx_bridge:
    external: true